# LSTM model using stock market prices

In this notebook, I will implement an LSTM model and train it based on stock market prices using data I get from Nasdaq.

- META: https://www.nasdaq.com/market-activity/stocks/meta/historical?page=1&rows_per_page=10&timeline=y10
- AMZN: https://www.nasdaq.com/market-activity/stocks/amzn/historical?page=1&rows_per_page=10&timeline=y10
- AAPL: https://www.nasdaq.com/market-activity/stocks/aapl/historical?page=1&rows_per_page=10&timeline=y10
- NFLX: https://www.nasdaq.com/market-activity/stocks/nflx/historical?page=1&rows_per_page=10&timeline=y10
- GOOGL: https://www.nasdaq.com/market-activity/stocks/googl/historical?page=1&rows_per_page=10&timeline=y10
- MSFT: https://www.nasdaq.com/market-activity/stocks/msft/historical?page=1&rows_per_page=10&timeline=y10

Although I have multiple data collected here, I will just focus on one data set (META) right now. Maybe I can do something later with more data sets.

Also, for this notebook, I will try to use the plotly package.

### Importing Packages and Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import plotly.express as px
import plotly.graph_objects as go

from sklearn.preprocessing import MinMaxScaler

### Data Collection

In [67]:
df_META = pd.read_csv("data/META.csv")
df_AMZN = pd.read_csv("data/AMZN.csv")
df_AAPL = pd.read_csv("data/AAPL.csv")
df_NFLX = pd.read_csv("data/NFLX.csv")
df_GOOGL = pd.read_csv("data/GOOGL.csv")
df_MSFT = pd.read_csv("data/MSFT.csv")

print(df_META.shape)
df_META.head()

(2514, 6)

         Date Close/Last    Volume      Open       High      Low
0  07/03/2025    $719.01   8601653   $726.61    $729.03  $714.42
1  07/02/2025    $713.57   9336740  $715.325    $720.30  $712.80
2  07/01/2025    $719.22  13431250  $736.875  $737.7499  $715.37
3  06/30/2025    $738.09  15402110   $744.55    $747.90  $734.25
4  06/27/2025    $733.63  18775740  $726.515    $735.43  $725.86

### Data Wrangling/Cleaning

In [68]:

df_META = df_META.rename(columns = {'Close/Last' : 'Close'})
df_AMZN = df_AMZN.rename(columns = {'Close/Last' : 'Close'})
df_AAPL = df_AAPL.rename(columns = {'Close/Last' : 'Close'})
df_NFLX = df_NFLX.rename(columns = {'Close/Last' : 'Close'})
df_GOOGL = df_GOOGL.rename(columns = {'Close/Last' : 'Close'})
df_MSFT = df_MSFT.rename(columns = {'Close/Last' : 'Close'})

collected_data = {"META":df_META, "AMZN":df_AMZN, "AAPL":df_AAPL, "NFLX": df_NFLX, "GOOGL": df_GOOGL, "MSFT": df_MSFT}

for temp_df in collected_data.values():
    temp_df['Close'] = temp_df['Close'].str[1:].astype(float)
    temp_df['Open'] = temp_df['Open'].str[1:].astype(float)
    temp_df['High'] = temp_df['High'].str[1:].astype(float)
    temp_df['Low'] = temp_df['Low'].str[1:].astype(float)
    temp_df['Date'] = pd.to_datetime(temp_df['Date'], format="%m/%d/%Y")


df_META.head()

        Date   Close    Volume     Open      High     Low
0 2025-07-03  719.01   8601653  726.610  729.0300  714.42
1 2025-07-02  713.57   9336740  715.325  720.3000  712.80
2 2025-07-01  719.22  13431250  736.875  737.7499  715.37
3 2025-06-30  738.09  15402110  744.550  747.9000  734.25
4 2025-06-27  733.63  18775740  726.515  735.4300  725.86

### Data Visualization

In [86]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=df_META['Date'], y=df_META['Close'], name='Close', marker={'color':'yellow'}, mode='lines'))
fig.add_trace(go.Scatter(x=df_META['Date'], y=df_META['High'], name='High', marker={'color':'green'}, mode='lines'))
fig.add_trace(go.Scatter(x=df_META['Date'], y=df_META['Low'], name='Low', marker={'color':'red'}, mode='lines'))

fig.update_layout(title="META stock prices",
                  xaxis_title="Date",
                  yaxis_title="Stock price")

fig.show()

### Create LSTM model